### ISSUE TITLE
Criar cronômetro de resposta do usuário

### ISSUE THREAD

**Issue by gp2902** [RE-RED/clooli#26]
Quando o bot envia uma mensagem de estado, um cronômetro deve:

Ao chegar a zero, enviar mensagem ao usuário e tomar uma decisão (escolher um estado predefinido);
Se o usuário responder antes do tempo acabar, o cronômetro é removido da aplicação, sem prejuizos.

https://stackoverflow.com/questions/45419723/python-timer-with-asyncio-coroutine

**Comment by emillyvc03** [comment]
Optamos por não adicionarmos esse recurso no nosso.
